export const movieData = [
  {
    Title: "Gun",
    Year: "2010",
    Rated: "R",
    Released: "05 Sep 2015",
    Runtime: "82 min",
    Genre: "Action, Crime, Thriller",
    Director: "Jessy Terrero",
    Writer: "50 Cent",
    Actors: "50 Cent, Val Kilmer, AnnaLynne McCord",
    Plot: "Angel is released from prison and is reunited with his friend Rich who helps him smuggle weapons in a gun-running ring. But Detroit police and the FBI have declared war on arms smuggling.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc0MDk3MjI1OV5BMl5BanBnXkFtZTcwNzg0MjIyMw@@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "3.8/10" }],
    Metascore: "N/A",
    imdbRating: "3.8",
    imdbVotes: "4,058",
    imdbID: "tt1560954",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Gun",
    Year: "2010",
    Rated: "R",
    Released: "05 Sep 2015",
    Runtime: "82 min",
    Genre: "Action, Crime, Thriller",
    Director: "Jessy Terrero",
    Writer: "50 Cent",
    Actors: "50 Cent, Val Kilmer, AnnaLynne McCord",
    Plot: "Angel is released from prison and is reunited with his friend Rich who helps him smuggle weapons in a gun-running ring. But Detroit police and the FBI have declared war on arms smuggling.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc0MDk3MjI1OV5BMl5BanBnXkFtZTcwNzg0MjIyMw@@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "3.8/10" }],
    Metascore: "N/A",
    imdbRating: "3.8",
    imdbVotes: "4,058",
    imdbID: "tt1560954",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Gun",
    Year: "2010",
    Rated: "R",
    Released: "05 Sep 2015",
    Runtime: "82 min",
    Genre: "Action, Crime, Thriller",
    Director: "Jessy Terrero",
    Writer: "50 Cent",
    Actors: "50 Cent, Val Kilmer, AnnaLynne McCord",
    Plot: "Angel is released from prison and is reunited with his friend Rich who helps him smuggle weapons in a gun-running ring. But Detroit police and the FBI have declared war on arms smuggling.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc0MDk3MjI1OV5BMl5BanBnXkFtZTcwNzg0MjIyMw@@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "3.8/10" }],
    Metascore: "N/A",
    imdbRating: "3.8",
    imdbVotes: "4,058",
    imdbID: "tt1560954",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Gun",
    Year: "2010",
    Rated: "R",
    Released: "05 Sep 2015",
    Runtime: "82 min",
    Genre: "Action, Crime, Thriller",
    Director: "Jessy Terrero",
    Writer: "50 Cent",
    Actors: "50 Cent, Val Kilmer, AnnaLynne McCord",
    Plot: "Angel is released from prison and is reunited with his friend Rich who helps him smuggle weapons in a gun-running ring. But Detroit police and the FBI have declared war on arms smuggling.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc0MDk3MjI1OV5BMl5BanBnXkFtZTcwNzg0MjIyMw@@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "3.8/10" }],
    Metascore: "N/A",
    imdbRating: "3.8",
    imdbVotes: "4,058",
    imdbID: "tt1560954",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Gun",
    Year: "2010",
    Rated: "R",
    Released: "05 Sep 2015",
    Runtime: "82 min",
    Genre: "Action, Crime, Thriller",
    Director: "Jessy Terrero",
    Writer: "50 Cent",
    Actors: "50 Cent, Val Kilmer, AnnaLynne McCord",
    Plot: "Angel is released from prison and is reunited with his friend Rich who helps him smuggle weapons in a gun-running ring. But Detroit police and the FBI have declared war on arms smuggling.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc0MDk3MjI1OV5BMl5BanBnXkFtZTcwNzg0MjIyMw@@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "3.8/10" }],
    Metascore: "N/A",
    imdbRating: "3.8",
    imdbVotes: "4,058",
    imdbID: "tt1560954",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Gun",
    Year: "2010",
    Rated: "R",
    Released: "05 Sep 2015",
    Runtime: "82 min",
    Genre: "Action, Crime, Thriller",
    Director: "Jessy Terrero",
    Writer: "50 Cent",
    Actors: "50 Cent, Val Kilmer, AnnaLynne McCord",
    Plot: "Angel is released from prison and is reunited with his friend Rich who helps him smuggle weapons in a gun-running ring. But Detroit police and the FBI have declared war on arms smuggling.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc0MDk3MjI1OV5BMl5BanBnXkFtZTcwNzg0MjIyMw@@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "3.8/10" }],
    Metascore: "N/A",
    imdbRating: "3.8",
    imdbVotes: "4,058",
    imdbID: "tt1560954",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Gun",
    Year: "2010",
    Rated: "R",
    Released: "05 Sep 2015",
    Runtime: "82 min",
    Genre: "Action, Crime, Thriller",
    Director: "Jessy Terrero",
    Writer: "50 Cent",
    Actors: "50 Cent, Val Kilmer, AnnaLynne McCord",
    Plot: "Angel is released from prison and is reunited with his friend Rich who helps him smuggle weapons in a gun-running ring. But Detroit police and the FBI have declared war on arms smuggling.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc0MDk3MjI1OV5BMl5BanBnXkFtZTcwNzg0MjIyMw@@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "3.8/10" }],
    Metascore: "N/A",
    imdbRating: "3.8",
    imdbVotes: "4,058",
    imdbID: "tt1560954",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
